<link rel="stylesheet" href="{{ asset('assets/frontend/css/bootstrap.min.css') }}">
<link rel="stylesheet" href="{{ asset('assets/frontend/css/owl.carousel.min.css') }}">
<link rel="stylesheet" href="{{ asset('assets/frontend/css/ticker-style.css') }}">
<link rel="stylesheet" href="{{ asset('assets/frontend/css/flaticon.css') }}">
<link rel="stylesheet" href="{{ asset('assets/frontend/css/slicknav.css') }}">
<link rel="stylesheet" href="{{ asset('assets/frontend/css/animate.min.css') }}">
<link rel="stylesheet" href="{{ asset('assets/frontend/css/magnific-popup.css') }}">
<link rel="stylesheet" href="{{ asset('assets/frontend/css/fontawesome-all.min.css') }}">
<link rel="stylesheet" href="{{ asset('assets/frontend/css/themify-icons.css') }}">
<link rel="stylesheet" href="{{ asset('assets/frontend/css/slick.css') }}">
<link rel="stylesheet" href="{{ asset('assets/frontend/css/nice-select.css') }}">
<link rel="stylesheet" href="{{ asset('assets/frontend/css/style.css') }}">
